version: '3'

services:
  trajectory:
    build: .
    command: python -m transhumus.trajectories.mona
    ports:
      - "1337:1337"
      - "1338:1338"
  websockets:
    build: .
    command: python -m transhumus.processors.websockets --main trajectory
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: ws.transhumus.${DOMAIN_NAME:-local}"
      traefik.docker.network: "proxytanet"
    networks:
      - proxytanet
      - default
  granier:
    build: .
    command: python -m transhumus.processors.granier --main trajectory
  granier_random:
    build: .
    command: python -m transhumus.inputs.granier_random --main trajectory
  simulator:
    build: .
    command: python -m transhumus.processors.simulator --main trajectory
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: transhumus.${DOMAIN_NAME:-local}, www.transhumus.${DOMAIN_NAME:-local}"
      traefik.docker.network: "proxytanet"
    networks:
      - proxytanet
      - default

networks:
  proxytanet:
    external: true
